name: Generate Pac-Man Animation
 
on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
 
jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
 
    steps:
      - name: Generate Pac-Man
        uses: Platane/snk@v3
        with:
          github_user_name: bayie27
          outputs: |
            dist/pacman.svg?type=pacman
            dist/pacman-dark.svg?type=pacman&palette=github-dark
 
      - name: Push to Output Branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
